### ISSUE TITLE
How to test cluster mode ?

### ISSUE THREAD

**Issue by drom89** [grblHAL/Plugins_laser#2]
Hi, i have problem (as always :) ).

So i generate gcode in LB with clusters under Smoothieware device preset, but i cant test it out.
LB is not communicating with grbl if i set Smoothieware device.

When i try to load it to iosender, i need to check every row by pressing OK
![image](https://user-images.githubusercontent.com/5219063/193335558-33d4d9e0-073d-4cdb-ba09-6bd041b65b86.png)

[VER:1.1f.20220928:]
[OPT:VNMSL,35,1024,3,0]
Target buffer size found
[AXS:3:XYZ]
[NEWOPT:ENUMS,RT+,REBOOT,TC,SED,RTC]
[FIRMWARE:grblHAL]
[NVS STORAGE:*FLASH]
[DRIVER:ESP32]
[DRIVER VERSION:220922]
[DRIVER OPTIONS:v4.3.4]
[BOARD:MKS DLC32 2.0]

**Comment by drom89** [comment]
Ok, i just found out, that i can test it with Candle, i will try it out.
[https://github.com/grblHAL/core/discussions/195](url)

**Comment by terjeio** [comment]
You have not enabled the [cluster plugin](https://github.com/grblHAL/ESP32/blob/22f9d9169aec7bee579b0d9343e0e505429eb3a1/main/CMakeLists.txt#L64)...

And you may have to change [an option in the plugin](https://github.com/grblHAL/Plugins_laser/blob/2e44ef976fc27d9b97115a7367c7842b1de6b71f/lb_clusters.c#L40-L42) if you do not have the latest (beta?) version of LightBurn? The S-values are less than or equal to 0 if you need to do that (it seems so from the error message above).

**Comment by drom89** [comment]
> You have not enabled the [cluster plugin](https://github.com/grblHAL/ESP32/blob/22f9d9169aec7bee579b0d9343e0e505429eb3a1/main/CMakeLists.txt#L64)...
> 
Yep i just added #define LB_CLUSTERS_ENABLE 1 to my_machine.h 

> And you may have to change [an option in the plugin](https://github.com/grblHAL/Plugins_laser/blob/2e44ef976fc27d9b97115a7367c7842b1de6b71f/lb_clusters.c#L40-L42) if you do not have the latest (beta?) version of LightBurn? The S-values are less than or equal to 0 if you need to do that (it seems so from the error message above).
> 

I have version 1.2.01 latest normal version.
will try it out, thanks.

**Comment by drom89** [comment]
[https://forum.lightburnsoftware.com/t/cluster-mode-for-grblhal/77711](url)

Little bit info from LB staff

It has actually been enabled for the next release (1.2.02) already, and Ortur has added support to it for their firmware, and so has Tim Rothman.

Cluster on G code devices has also been set up to allow up to 16 brightness values per cluster, and it looks for [CLUSTER:xx] as a response to the $I command. If it sees that response, it pulls the number out of the argument there, and uses that as the cluster size, clamped to be a value between 1 and 16.

Oz (Lead Dev/Owner) actually replied to that thread on LaserGRBL’s github - however left the chat once it devolved into implementing full image processing on the controllers
